[package]
name = "SpaceTravelSimulator"
version = "0.1.0"
edition = "2021"

[dependencies]
fastnoise-lite = "1.1.1"
minifb = "0.27.0"
nalgebra = "0.33.2"
nalgebra-glm = "0.19.0"
rand = "0.8.5"
tobj = "4.0.2"
